export const ERoutes = {
  HOME_PAGE: "/app",
  Anon_HOME_ROUTE: "/",
  LOGIN: "login",
  SIGN_UP: "signup",
  FEED: "feed",
  MESSAGES: "messages",
  CREATE_POST: "createPost",
  SEARCH: "search",
  ACTIVITY: "activity",
  PARK: "park/parkname",
  PROFILE: "p/:username",
  NOT_FOUND: "/not-found",
  CREATEPARK: "createpark",
};
